#!/usr/bin/env bash

# Ensure the Brewfile is available.
cd "$DOTFILES" || exit

# Check for Homebrew installation. If not installed, then install latest
# version. macOS comes with a system version of Ruby that can be used for this.
if ( brew --version ) < /dev/null > /dev/null 2>&1; then
    echo 'Homebrew is already installed!'
else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
fi

# Tap any third-party repositories.
brew tap homebrew/cask;
brew tap homeport/tap;
brew tap mdcurran/taps;
brew tap nats-io/nats-tools;
brew tap oven-sh/bun;
brew tap speakeasy-api/homebrew-tap;

# Install or upgrade.
brew bundle;

# Clean-up and diagnose any potential problems.
brew cleanup && brew doctor;

# Install any non-Homebrew-managed software.
for FILENAME in scripts/*.sh; do
    sh $FILENAME;
done

# Remove quarantine attribute from Homebrew-managed ClickHouse installation.
xattr -d com.apple.quarantine /opt/homebrew/bin/clickhouse

exit 0;
