#!/usr/bin/env bash

# Ensure the Brewfile is available.
cd "$DOTFILES" || exit

# Check for Homebrew installation. If not installed, then install latest
# version. macOS comes with a system version of Ruby that can be used for this.
if ( brew --version ) < /dev/null > /dev/null 2>&1; then
    echo 'Homebrew is already installed!'
else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
fi

# Tap any third-party repositories.
brew tap homebrew/cask;
brew tap mdcurran/taps;
brew tap modularml/packages;
brew tap nats-io/nats-tools;
brew tap oven-sh/bun;
brew tap speakeasy-api/homebrew-tap;

# Check that the Homebrew bundle functionality is enabled, then install the
# dependencies listed in the Brewfile.
if ( brew bundle check; ) < /dev/null > /dev/null 2>&1; then
    echo 'Brewfiles enabled'
else
    brew tap Homebrew/bundle;
fi

# Generate the lock file.
brew bundle;

# Clean-up and diagnose any potential problems.
brew cleanup && brew doctor;

exit 0;
