# Ensures all applications to be installed to the ~/Applications directory.
cask_args appdir: "~/Applications"

# Software
brew "atuin"
brew "bat"
brew "benthos"
brew "bun"
brew "cask"
brew "clang-format"
brew "cmake"
brew "coreutils"  # Update the outdated default macOS ones
brew "dive"
brew "doctl"
brew "duckdb"
brew "elixir"
brew "etcd"
brew "fd"
brew "flyctl"
brew "git"
brew "gnuplot"
brew "go"
brew "graphviz"
brew "gron"
brew "httpie"
brew "hugo"
brew "jq"
brew "kind"
brew "kubectl"
brew "llvm"
brew "lua-language-server"
brew "luarocks"
brew "mas"  # Mac App Store manager
brew "modular"
brew "node"
brew "nvm"
brew "mdcurran/taps/note"
brew "nats-io/nats-tools/nats"
brew "nats-server"
brew "neovim"
brew "openjdk@17"
brew "pass"
brew "pdm"
brew "postgresql"
brew "protobuf"
brew "pyenv"
brew "rbenv"
brew "rclone"
brew "redis"
brew "ripgrep"
brew "ruby-build"
brew "shellcheck"
brew "speakeasy"
brew "sqlc"
brew "stern"
brew "terraform"
brew "vim"
brew "yarn"
brew "yq"
brew "zig"

# Applications
cask "calibre"
cask "clickhouse"
cask "dash"
cask "discord"
cask "docker"
cask "flux"  # f.lux
cask "firefox"
cask "insomnia"
cask "iterm2"
cask "ngrok"
cask "notion"
cask "obsidian"
cask "postman"
cask "rar"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "visual-studio-code"
cask "wezterm"
cask "zed"
cask "zoom"

# Fonts
cask "font-jetbrains-mono"

# Mac App Store
mas "Magnet", id: 441258766
mas "Things 3", id: 904280696
