format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$character"""

add_newline = false
command_timeout = 360000

[directory]
style = "blue"
truncation_length = 1

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[git_branch]
format = "\\([$branch]($style)"
style = "cyan"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)\\) ]($style)"
style = "white"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style)"
style = "bright-black"
